name = "FractionalCalculus"
uuid = "638fb199-4bb2-4014-80c8-6dc0d90f156b"
license = "MIT"
authors = ["Qingyu Qu <erikqqy123@gmail.com>"]
version = "0.1.1"

[deps]
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
QuadGK = "2.4.2"
SpecialFunctions = "1.6.2"
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
